/* Auto-generated by export_asset_table.py -- DO NOT EDIT */
/* Generated from: ../../projects/demo-a2/ASSETS.DB */

#ifndef NB_ASSET_TABLE_H
#define NB_ASSET_TABLE_H

/* Image asset key->ID lookup (for cmd_bg) */
static const struct { const char *key; int id; } asset_map[] = {
    {"splbg", 0},
    {"logo", 4},
    {"mainmenu", 5},
    {"powered", 6},
    {"seasidebg", 7},
    {"yellow_grid", 13},
    {"pink_grid", 14},
    {NULL, 0}
};

/* Sprite asset key->ID lookup (for cmd_char) */
static const struct { const char *key; int id; } spr_asset_map[] = {
    {"fei-normal", 1},
    {"ira-normal", 2},
    {"neon-normal", 3},
    {"fei-sad", 8},
    {"fei-smile", 9},
    {"fei-surprised", 10},
    {"fei-swimming", 11},
    {"ira-sad", 12},
    {NULL, 0}
};

/* Character key->ID mapping */
static const struct { const char *key; int id; const char *name; } char_map[] = {
    {"fei", 9, "Fei"},
    {"ira", 10, "Ira"},
    {"neon", 11, "Neon"},
    {NULL, 0, NULL}
};

/* Expression lookup: (char_id, expr_name) -> asset_id */
static const struct { int char_id; const char *expr; int asset_id; } expr_map[] = {
    {9, "normal", 1},
    {9, "sad", 8},
    {9, "smile", 9},
    {9, "surprised", 10},
    {9, "swimming", 11},
    {10, "normal", 2},
    {10, "sad", 12},
    {11, "normal", 3},
    {-1, NULL, 0}
};

/* ANI asset key->ID lookup (for playanima) */
static const struct { const char *name; int id; } anim_map[] = {
    {"testfull", 17},
    {"testcine", 18},
    {NULL, 0}
};

/* CG asset key->ID lookup (for cg command) */
static const struct { const char *key; int id; } cg_map[] = {
    {"cg01", 19},
    {"cg02", 20},
    {NULL, 0}
};

/* Number of registered CG assets */
#define CG_COUNT 2


#endif /* NB_ASSET_TABLE_H */
