/* Auto-generated by export_asset_table.py -- DO NOT EDIT */
/* Generated from: ../../projects/animatest/ASSETS.DB */

#ifndef NB_ASSET_TABLE_H
#define NB_ASSET_TABLE_H

/* Image asset key->ID lookup (for cmd_bg) */
static const struct { const char *key; int id; } asset_map[] = {
    {"animatest-f1", 0},
    {"animatest-f2", 1},
    {"naizlogo", 2},
    {"powered", 3},
    {"mainmenu", 4},
    {NULL, 0}
};

/* Sprite asset key->ID lookup (for cmd_char) */
static const struct { const char *key; int id; } spr_asset_map[] = {
    {"__dummy__", 0},
    {NULL, 0}
};

/* Character key->ID mapping */
static const struct { const char *key; int id; const char *name; } char_map[] = {
    {NULL, 0, NULL}
};

/* Expression lookup: (char_id, expr_name) -> asset_id */
static const struct { int char_id; const char *expr; int asset_id; } expr_map[] = {
    {-1, NULL, 0}
};

/* ANI asset key->ID lookup (for playanima) */
static const struct { const char *name; int id; } anim_map[] = {
    {"testfull", 5},
    {"testcine", 6},
    {NULL, 0}
};

/* CG asset key->ID lookup (for cg command) */
static const struct { const char *key; int id; } cg_map[] = {
    {"__dummy__", 0},
    {NULL, 0}
};

/* Number of registered CG assets */
#define CG_COUNT 0

/* Gallery-grid thumbnail key->ID lookup (parallel to cg_map; 0 = none) */
static const struct { const char *key; int id; } cg_thumb_map[] = {
    {"__dummy__", 0},
    {NULL, 0}
};

/* Number of registered gallery-grid thumbnails */
#define CG_THUMB_COUNT 0

/* Shared type for registered audio assets */
typedef struct { const char *name; int id; } AudioAssetMap;

/* BGM asset key->ID lookup (for bgm command) */
static const AudioAssetMap bgm_map[] = {
    {"__dummy__", 0},
    {NULL, 0}
};

/* SE asset key->ID lookup (for sound command) */
static const AudioAssetMap snd_map[] = {
    {"__dummy__", 0},
    {NULL, 0}
};

/* Voice asset key->ID lookup (for voice command) */
static const AudioAssetMap voice_map[] = {
    {"__dummy__", 0},
    {NULL, 0}
};


#endif /* NB_ASSET_TABLE_H */
