/* Auto-generated by export_config.py -- DO NOT EDIT */
/* Generated from: ../../projects/demo-a2/config.toml */

#ifndef NAIZ_CONFIG_H
#define NAIZ_CONFIG_H

#define NAIZ_VERSION "0.3.026"
#define NAIZ_DLGSTYLE 5
#define NAIZ_BTNSTYLE 2
#define NAIZ_BLACKLETTER_TITLE 0
#define NAIZ_BLACKLETTER_DIALOG 0
#define NAIZ_DEFAULT_LANG "eng"

#define NAIZ_TRANSITION_TYPE 6
#define NAIZ_TRANSITION_FRAMES 16

#endif /* NAIZ_CONFIG_H */
