/* Auto-generated by export_config.py -- DO NOT EDIT */
/* Generated from: ../../projects/demo-a2/config.toml */

#ifndef NAIZ_CONFIG_H
#define NAIZ_CONFIG_H

#define NAIZ_TRANSITION_TYPE 6
#define NAIZ_TRANSITION_FRAMES 16

#endif /* NAIZ_CONFIG_H */
