/* Auto-generated by export_vars.py -- DO NOT EDIT */
/* Generated from: ../../projects/demo-a2/variables.json */

#ifndef NB_VAR_DEFS_H
#define NB_VAR_DEFS_H

#include "nb_var_table.h"

static const NbVarDef var_defs[NB_VAR_COUNT] = {
    {"bond_fei", "Fei好感度", "Fei对玩家的好感度", 0, 0, 100},
    {"bond_ira", "Ira好感度", "Ira对玩家的好感度", 0, 0, 100},
    {"bond_neon", "Neon好感度", "Neon对玩家的好感度", 0, 0, 100},
};

#endif /* NB_VAR_DEFS_H */
