/* Auto-generated by export_vars.py -- DO NOT EDIT */
/* Generated from: ../../projects/demo-a2/variables.json */

#ifndef NB_VAR_TABLE_H
#define NB_VAR_TABLE_H

#define NB_VAR_COUNT 3

typedef struct {
    const char *id;
    const char *name;
    const char *desc;
    int initial;
    int min;
    int max;
} NbVarDef;

#endif /* NB_VAR_TABLE_H */
