#!/usr/bin/env python3
"""Shared C header generation helpers for the export_* generators.

Used by export_asset_table.py, export_vars.py and export_config.py so the
generator boilerplate (escape, guard, header preamble) lives in one place.
"""

import os


def escape(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


def header_preamble(generator_name, src_path, output_path, guard):
    """Return the opening lines of a generated C header."""
    return [
        f'/* Auto-generated by {generator_name} -- DO NOT EDIT */',
        f'/* Generated from: {os.path.relpath(src_path, os.path.dirname(output_path) or ".")} */',
        '',
        f'#ifndef {guard}',
        f'#define {guard}',
        '',
    ]


def header_footer(guard):
    return ['', f'#endif /* {guard} */', '']


def write_header(output_path, lines):
    """Write generated header lines, returning byte count written."""
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))
    return sum(len(l) + 1 for l in lines)
